namespace CluedIn.Crawling.Dynamics365.Core.Models
{
    public class CRM_LEAD
    {
        public string accountid { get; set; }
        public string accountiddsc { get; set; }
        public string accountidname { get; set; }
        public string accountidyominame { get; set; }
        public string address1_addressid { get; set; }
        public string address1_addresstypecode { get; set; }
        public string address1_addresstypecodename { get; set; }
        public string address1_city { get; set; }
        public string address1_composite { get; set; }
        public string address1_country { get; set; }
        public string address1_county { get; set; }
        public string address1_fax { get; set; }
        public string address1_latitude { get; set; }
        public string address1_line1 { get; set; }
        public string address1_line2 { get; set; }
        public string address1_line3 { get; set; }
        public string address1_longitude { get; set; }
        public string address1_name { get; set; }
        public string address1_postalcode { get; set; }
        public string address1_postofficebox { get; set; }
        public string address1_shippingmethodcode { get; set; }
        public string address1_shippingmethodcodename { get; set; }
        public string address1_stateorprovince { get; set; }
        public string address1_telephone1 { get; set; }
        public string address1_telephone2 { get; set; }
        public string address1_telephone3 { get; set; }
        public string address1_upszone { get; set; }
        public string address1_utcoffset { get; set; }
        public string address2_addressid { get; set; }
        public string address2_addresstypecode { get; set; }
        public string address2_addresstypecodename { get; set; }
        public string address2_city { get; set; }
        public string address2_composite { get; set; }
        public string address2_country { get; set; }
        public string address2_county { get; set; }
        public string address2_fax { get; set; }
        public string address2_latitude { get; set; }
        public string address2_line1 { get; set; }
        public string address2_line2 { get; set; }
        public string address2_line3 { get; set; }
        public string address2_longitude { get; set; }
        public string address2_name { get; set; }
        public string address2_postalcode { get; set; }
        public string address2_postofficebox { get; set; }
        public string address2_shippingmethodcode { get; set; }
        public string address2_shippingmethodcodename { get; set; }
        public string address2_stateorprovince { get; set; }
        public string address2_telephone1 { get; set; }
        public string address2_telephone2 { get; set; }
        public string address2_telephone3 { get; set; }
        public string address2_upszone { get; set; }
        public string address2_utcoffset { get; set; }
        public string ap_afslutlead { get; set; }
        public string ap_afslutleadutc { get; set; }
        public string ap_aftale { get; set; }
        public string ap_aftalename { get; set; }
        public string ap_alder { get; set; }
        public string ap_alleredemedlem { get; set; }
        public string ap_alleredemedlemname { get; set; }
        public string ap_ambassadoer { get; set; }
        public string ap_amb_ledig { get; set; }
        public string ap_amb_ledigname { get; set; }
        public string ap_andetnr { get; set; }
        public string ap_andetnrname { get; set; }
        public string ap_anmodacceptindmeldelse { get; set; }
        public string ap_anmodacceptindmeldelsename { get; set; }
        public string ap_antaldageget { get; set; }
        public string ap_antaldagegetint { get; set; }
        public string ap_antalkontaktforsoegifase1 { get; set; }
        public string ap_antalkontaktforsoegifase3 { get; set; }
        public string ap_antalkontaktforsog { get; set; }
        public string ap_birthday { get; set; }
        public string ap_birthdayutc { get; set; }
        public string ap_branchekode { get; set; }
        public string ap_brevstatus { get; set; }
        public string ap_brevstatusname { get; set; }
        public string ap_checkimodulus { get; set; }
        public string ap_checkimodulusname { get; set; }
        public string ap_country { get; set; }
        public string ap_countryname { get; set; }
        public string ap_cpr6cifre { get; set; }
        public string ap_cvrnummer { get; set; }
        public string ap_datoforfoersteopkaldifasen { get; set; }
        public string ap_datoforfoersteopkaldifasenutc { get; set; }
        public string ap_datoopkald { get; set; }
        public string ap_datoopkaldutc { get; set; }
        public string ap_diverse { get; set; }
        public string ap_diversename { get; set; }
        public string ap_dybderesultat { get; set; }
        public string ap_dybderesultatname { get; set; }
        public string ap_emailadmin { get; set; }
        public string ap_emailadminname { get; set; }
        public string ap_fejllead { get; set; }
        public string ap_fejlleadname { get; set; }
        public string ap_forening { get; set; }
        public string ap_foreningname { get; set; }
        public string ap_foreningsdomain { get; set; }
        public string ap_googlesoegeord { get; set; }
        public string ap_handling { get; set; }
        public string ap_handlingname { get; set; }
        public string ap_henvisendekonsulent { get; set; }
        public string ap_henvisendekonsulentname { get; set; }
        public string ap_henvisendekonsulentyominame { get; set; }
        public string ap_henvisning { get; set; }
        public string ap_henvisningname { get; set; }
        public string ap_hvervepakkeekstrainfo { get; set; }
        public string ap_hvervepakkestatus { get; set; }
        public string ap_hvervepakkestatusdato { get; set; }
        public string ap_hvervepakkestatusdatoutc { get; set; }
        public string ap_hvervepakkestatusname { get; set; }
        public string ap_hvervepakketype { get; set; }
        public string ap_hvervepakketypename { get; set; }
        public string ap_indmeldelseaccepteret { get; set; }
        public string ap_indmeldelseaccepteretname { get; set; }
        public string ap_krydssalg { get; set; }
        public string ap_krydssalgname { get; set; }
        public string ap_kundeemnetype { get; set; }
        public string ap_kundeemnetypename { get; set; }
        public string ap_log { get; set; }
        public string ap_ltdaekning { get; set; }
        public string ap_ltikraftdato { get; set; }
        public string ap_ltikraftdatoutc { get; set; }
        public string ap_ltkarens { get; set; }
        public string ap_ltperiode { get; set; }
        public string ap_medlemindmeldelseid { get; set; }
        public string ap_medlemindmeldelseidname { get; set; }
        public string ap_medlemsnummer { get; set; }
        public string ap_member { get; set; }
        public string ap_membername { get; set; }
        public string ap_mersalgforsikringerhelbred { get; set; }
        public string ap_mersalgforsikringerhelbredname { get; set; }
        public string ap_mersalgforsikringerkritisk { get; set; }
        public string ap_mersalgforsikringerkritiskname { get; set; }
        public string ap_mersalgforsikringerlak { get; set; }
        public string ap_mersalgforsikringerlakname { get; set; }
        public string ap_mersalgforsikringerlt { get; set; }
        public string ap_mersalgforsikringerltname { get; set; }
        public string ap_mersalgforsikringerulykke { get; set; }
        public string ap_mersalgforsikringerulykkename { get; set; }
        public string ap_mersalgjobrettetcoaching { get; set; }
        public string ap_mersalgjobrettetcoachingname { get; set; }
        public string ap_mersalgjobrettetdigitalmarkedsfoering { get; set; }
        public string ap_mersalgjobrettetdigitalmarkedsfoeringname { get; set; }
        public string ap_mersalgjobrettetelearning { get; set; }
        public string ap_mersalgjobrettetelearningname { get; set; }
        public string ap_mersalgjobrettethr { get; set; }
        public string ap_mersalgjobrettethrname { get; set; }
        public string ap_mersalgjobrettetkommunikation { get; set; }
        public string ap_mersalgjobrettetkommunikationname { get; set; }
        public string ap_mersalgjobrettetlean { get; set; }
        public string ap_mersalgjobrettetleanname { get; set; }
        public string ap_mersalgjobrettetledelse { get; set; }
        public string ap_mersalgjobrettetledelsename { get; set; }
        public string ap_mersalgjobrettetoekonomi { get; set; }
        public string ap_mersalgjobrettetoekonominame { get; set; }
        public string ap_mersalgjobrettetprojekt { get; set; }
        public string ap_mersalgjobrettetprojektname { get; set; }
        public string ap_mersalgjobrettetsalg { get; set; }
        public string ap_mersalgjobrettetsalgname { get; set; }
        public string ap_mersalgnytleadkc { get; set; }
        public string ap_mersalgnytleadkcname { get; set; }
        public string ap_mersalgnytleadmgm { get; set; }
        public string ap_mersalgnytleadmgmname { get; set; }
        public string ap_mersalgnytleadnyhedsbrev { get; set; }
        public string ap_mersalgnytleadnyhedsbrevname { get; set; }
        public string ap_mersalgnytleadpension { get; set; }
        public string ap_mersalgnytleadpensionname { get; set; }
        public string ap_mersalgnytleadprivatforsikringer { get; set; }
        public string ap_mersalgnytleadprivatforsikringername { get; set; }
        public string ap_mgm { get; set; }
        public string ap_mgmar50 { get; set; }
        public string ap_mgmar50name { get; set; }
        public string ap_mgmforkertnummer { get; set; }
        public string ap_mgmforkertnummername { get; set; }
        public string ap_mgmformangekontaktforsog { get; set; }
        public string ap_mgmformangekontaktforsogname { get; set; }
        public string ap_mgmhvervepakke { get; set; }
        public string ap_mgmhvervepakkename { get; set; }
        public string ap_mgmikkeinteresseret { get; set; }
        public string ap_mgmikkeinteresseretname { get; set; }
        public string ap_mgmikkeoptagelsesberettiget { get; set; }
        public string ap_mgmikkeoptagelsesberettigetname { get; set; }
        public string ap_mgmlead { get; set; }
        public string ap_mgmleadgave { get; set; }
        public string ap_mgmleadname { get; set; }
        public string ap_mgmname { get; set; }
        public string ap_mgmoverflyt { get; set; }
        public string ap_mgmoverflytname { get; set; }
        public string ap_mgmstatus { get; set; }
        public string ap_mgmstatusname { get; set; }
        public string ap_mgmvenderselvtilbage { get; set; }
        public string ap_mgmvenderselvtilbagename { get; set; }
        public string ap_midlertidigphoner { get; set; }
        public string ap_midlertidigphonername { get; set; }
        public string ap_midlertidigphoneryominame { get; set; }
        public string ap_moede { get; set; }
        public string ap_moedename { get; set; }
        public string ap_nuvaerendeselskab { get; set; }
        public string ap_nuvaerendeselskabname { get; set; }
        public string ap_omraade { get; set; }
        public string ap_omraadename { get; set; }
        public string ap_onsker { get; set; }
        public string ap_onskername { get; set; }
        public string ap_opkaldskonfiguration { get; set; }
        public string ap_opkaldskonfigurationname { get; set; }
        public string ap_partnerinitialer { get; set; }
        public string ap_phonerresultat { get; set; }
        public string ap_phonerresultatname { get; set; }
        public string ap_rating { get; set; }
        public string ap_ratingint { get; set; }
        public string ap_ratingname { get; set; }
        public string ap_renvask { get; set; }
        public string ap_renvaskname { get; set; }
        public string ap_resultatdimensionalleredemedlem { get; set; }
        public string ap_resultatdimensionalleredemedlemname { get; set; }
        public string ap_resultatdimensionikkeoptagelsesberettiget { get; set; }
        public string ap_resultatdimensionikkeoptagelsesberettigetname { get; set; }
        public string ap_resultatdimensioningeninteresse { get; set; }
        public string ap_resultatdimensioningeninteressename { get; set; }
        public string ap_resultatdimensionkrydssalg { get; set; }
        public string ap_resultatdimensionkrydssalgname { get; set; }
        public string ap_resultatdimensionlead { get; set; }
        public string ap_resultatdimensionleadname { get; set; }
        public string ap_resultatdimensionnytsalg { get; set; }
        public string ap_resultatdimensionnytsalgname { get; set; }
        public string ap_resultofphonecall { get; set; }
        public string ap_resultofphonecallname { get; set; }
        public string ap_saelger { get; set; }
        public string ap_saelgername { get; set; }
        public string ap_salgskanal { get; set; }
        public string ap_salgskanalname { get; set; }
        public string ap_salgsopkaldstype { get; set; }
        public string ap_salgsopkaldstypename { get; set; }
        public string ap_segment { get; set; }
        public string ap_segmentname { get; set; }
        public string ap_sidstehandlingdato { get; set; }
        public string ap_sidstehandlingdatoutc { get; set; }
        public string ap_slutdatoifasen { get; set; }
        public string ap_slutdatoifasenutc { get; set; }
        public string ap_slutdatoomfordeling { get; set; }
        public string ap_slutdatoomfordelingutc { get; set; }
        public string ap_sms { get; set; }
        public string ap_smsname { get; set; }
        public string ap_status { get; set; }
        public string ap_statusname { get; set; }
        public string ap_talsmand { get; set; }
        public string ap_talsmandname { get; set; }
        public string ap_telefonsvarer { get; set; }
        public string ap_telefonsvarername { get; set; }
        public string ap_tidtaeffesbedst { get; set; }
        public string ap_tidtaeffesbedstname { get; set; }
        public string ap_tilbudsendt { get; set; }
        public string ap_tilbudsendtname { get; set; }
        public string ap_tildel { get; set; }
        public string ap_tildelname { get; set; }
        public string ap_tilfredshed { get; set; }
        public string ap_tilfredshedname { get; set; }
        public string ap_typetelefon { get; set; }
        public string ap_ulykkesforsikring { get; set; }
        public string ap_ulykkesforsikringname { get; set; }
        public string ap_ventantaldage { get; set; }
        public string ap_ventantaldageint { get; set; }
        public string ap_ventstatus { get; set; }
        public string ap_ventstatusname { get; set; }
        public string ap_virksomhedstiftelsesdato { get; set; }
        public string ap_virksomhedstiftelsesdatoutc { get; set; }
        public string ap_wbdagesidenoprettelse { get; set; }
        public string ap_wbmedlemskab { get; set; }
        public string ap_wbmedlemskabname { get; set; }
        public string ap_wbnyakasse { get; set; }
        public string ap_wbnystilling { get; set; }
        public string ap_wbnystillingmodulus { get; set; }
        public string ap_wbnystillingmodulusname { get; set; }
        public string ap_wboprettelsedatoudmeldelse { get; set; }
        public string ap_wboprettelsedatoudmeldelseutc { get; set; }
        public string ap_wboprettetmodulus { get; set; }
        public string ap_wboprettetmodulusname { get; set; }
        public string ap_wbudmeldesaf { get; set; }
        public string ap_wbudmeldesafname { get; set; }
        public string ap_winback { get; set; }
        public string ap_winbackname { get; set; }
        public string ap_workflowstatus { get; set; }
        public string ap_workflowstatusname { get; set; }
        public string budgetamount { get; set; }
        public string budgetamount_base { get; set; }
        public string budgetstatus { get; set; }
        public string budgetstatusname { get; set; }
        public string campaignid { get; set; }
        public string campaigniddsc { get; set; }
        public string campaignidname { get; set; }
        public string companyname { get; set; }
        public string confirminterest { get; set; }
        public string confirminterestname { get; set; }
        public string contactid { get; set; }
        public string contactiddsc { get; set; }
        public string contactidname { get; set; }
        public string contactidyominame { get; set; }
        public string createdby { get; set; }
        public string createdbydsc { get; set; }
        public string createdbyname { get; set; }
        public string createdbyyominame { get; set; }
        public string createdon { get; set; }
        public string createdonutc { get; set; }
        public string createdonbehalfby { get; set; }
        public string createdonbehalfbydsc { get; set; }
        public string createdonbehalfbyname { get; set; }
        public string createdonbehalfbyyominame { get; set; }
        public string customerid { get; set; }
        public string customeriddsc { get; set; }
        public string customeridname { get; set; }
        public string customeridtype { get; set; }
        public string customeridyominame { get; set; }
        public string decisionmaker { get; set; }
        public string decisionmakername { get; set; }
        public string description { get; set; }
        public string donotbulkemail { get; set; }
        public string donotbulkemailname { get; set; }
        public string donotemail { get; set; }
        public string donotemailname { get; set; }
        public string donotfax { get; set; }
        public string donotfaxname { get; set; }
        public string donotphone { get; set; }
        public string donotphonename { get; set; }
        public string donotpostalmail { get; set; }
        public string donotpostalmailname { get; set; }
        public string donotsendmarketingmaterialname { get; set; }
        public string donotsendmm { get; set; }
        public string emailaddress1 { get; set; }
        public string emailaddress2 { get; set; }
        public string emailaddress3 { get; set; }
        public string entityimageid { get; set; }
        public string entityimage_timestamp { get; set; }
        public string entityimage_url { get; set; }
        public string estimatedamount { get; set; }
        public string estimatedamount_base { get; set; }
        public string estimatedclosedate { get; set; }
        public string estimatedclosedateutc { get; set; }
        public string estimatedvalue { get; set; }
        public string evaluatefit { get; set; }
        public string evaluatefitname { get; set; }
        public string exchangerate { get; set; }
        public string fax { get; set; }
        public string firstname { get; set; }
        public string fullname { get; set; }
        public string importsequencenumber { get; set; }
        public string industrycode { get; set; }
        public string industrycodename { get; set; }
        public string initialcommunication { get; set; }
        public string initialcommunicationname { get; set; }
        public string isprivatename { get; set; }
        public string jobtitle { get; set; }
        public string lastname { get; set; }
        public string lastusedincampaign { get; set; }
        public string lastusedincampaignutc { get; set; }
        public string lder_ekstra_information { get; set; }
        public string lder_intern_besked { get; set; }
        public string lder_intern_beskedname { get; set; }
        public string lder_intern_besked_fra_mr { get; set; }
        public string lder_mersalg_forsikringer_ulykke_barn { get; set; }
        public string lder_mersalg_forsikringer_ulykke_barnname { get; set; }
        public string lder_mersalg_forsikringer_ulykke_samlever { get; set; }
        public string lder_mersalg_forsikringer_ulykke_samlevername { get; set; }
        public string lder_opret_aftale_i_outlook { get; set; }
        public string lder_opret_aftale_i_outlookname { get; set; }
        public string lder_sidste_faktisk_slutning { get; set; }
        public string lder_sidste_faktisk_slutningutc { get; set; }
        public string lder_svar_til_mr { get; set; }
        public string lder_teledata_navn { get; set; }
        public string lder_uddyb_dybderesultat { get; set; }
        public string lder_uddyb_dybderesultat_winback { get; set; }
        public string lder_uddyb_dybderesult_ikkeoptagelseberettiget { get; set; }
        public string lder_uddyb_winbackaarsag { get; set; }
        public string lder_virksomhedstype { get; set; }
        public string leadid { get; set; }
        public string leadqualitycode { get; set; }
        public string leadqualitycodename { get; set; }
        public string leadsourcecode { get; set; }
        public string leadsourcecodename { get; set; }
        public string lh_eksternid { get; set; }
        public string masterid { get; set; }
        public string masterleadiddsc { get; set; }
        public string masterleadidname { get; set; }
        public string masterleadidyominame { get; set; }
        public string merged { get; set; }
        public string mergedname { get; set; }
        public string middlename { get; set; }
        public string mobilephone { get; set; }
        public string modifiedby { get; set; }
        public string modifiedbydsc { get; set; }
        public string modifiedbyname { get; set; }
        public string modifiedbyyominame { get; set; }
        public string modifiedon { get; set; }
        public string modifiedonutc { get; set; }
        public string modifiedonbehalfby { get; set; }
        public string modifiedonbehalfbydsc { get; set; }
        public string modifiedonbehalfbyname { get; set; }
        public string modifiedonbehalfbyyominame { get; set; }
        public string need { get; set; }
        public string needname { get; set; }
        public string nn_lastupdated { get; set; }
        public string nn_lastupdatedutc { get; set; }
        public string nn_links { get; set; }
        public string nn_tdcid { get; set; }
        public string nn_updateprotected { get; set; }
        public string nn_updateprotectedname { get; set; }
        public string numberofemployees { get; set; }
        public string originatingcaseid { get; set; }
        public string originatingcaseidname { get; set; }
        public string overriddencreatedon { get; set; }
        public string overriddencreatedonutc { get; set; }
        public string ownerid { get; set; }
        public string owneriddsc { get; set; }
        public string owneridname { get; set; }
        public string owneridtype { get; set; }
        public string owneridyominame { get; set; }
        public string owningbusinessunit { get; set; }
        public string owningteam { get; set; }
        public string owninguser { get; set; }
        public string pager { get; set; }
        public string parentaccountid { get; set; }
        public string parentaccountidname { get; set; }
        public string parentaccountidyominame { get; set; }
        public string parentcontactid { get; set; }
        public string parentcontactidname { get; set; }
        public string parentcontactidyominame { get; set; }
        public string participatesinworkflow { get; set; }
        public string participatesinworkflowname { get; set; }
        public string preferredcontactmethodcode { get; set; }
        public string preferredcontactmethodcodename { get; set; }
        public string prioritycode { get; set; }
        public string prioritycodename { get; set; }
        public string processid { get; set; }
        public string purchaseprocess { get; set; }
        public string purchaseprocessname { get; set; }
        public string purchasetimeframe { get; set; }
        public string purchasetimeframename { get; set; }
        public string qualificationcomments { get; set; }
        public string qualifyingopportunityid { get; set; }
        public string qualifyingopportunityidname { get; set; }
        public string relatedobjectid { get; set; }
        public string relatedobjectidname { get; set; }
        public string revenue { get; set; }
        public string revenue_base { get; set; }
        public string salesstage { get; set; }
        public string salesstagecode { get; set; }
        public string salesstagecodename { get; set; }
        public string salesstagename { get; set; }
        public string salutation { get; set; }
        public string schedulefollowup_prospect { get; set; }
        public string schedulefollowup_prospectutc { get; set; }
        public string schedulefollowup_qualify { get; set; }
        public string schedulefollowup_qualifyutc { get; set; }
        public string sic { get; set; }
        public string stageid { get; set; }
        public string statecode { get; set; }
        public string statecodename { get; set; }
        public string statuscode { get; set; }
        public string statuscodename { get; set; }
        public string subject { get; set; }
        public string telephone1 { get; set; }
        public string telephone2 { get; set; }
        public string telephone3 { get; set; }
        public string timezoneruleversionnumber { get; set; }
        public string transactioncurrencyid { get; set; }
        public string transactioncurrencyiddsc { get; set; }
        public string transactioncurrencyidname { get; set; }
        public string traversedpath { get; set; }
        public string utcconversiontimezonecode { get; set; }
        public string versionnumber { get; set; }
        public string websiteurl { get; set; }
        public string yomicompanyname { get; set; }
        public string yomifirstname { get; set; }
        public string yomifullname { get; set; }
        public string yomilastname { get; set; }
        public string yomimiddlename { get; set; }
        public string crm_moneyformatstring { get; set; }
        public string crm_priceformatstring { get; set; }
    }
}
