using System;

namespace CluedIn.Crawling.Dynamics365.Core.Models
{
    public class CRM_CONTACT
    {
        public string lder_fremtidig_foreningName { get; private set; }
        public string EntityImage_URL { get; private set; }
        public string CreatedOnBehalfByName { get; private set; }
        public string lder_forbundsenhedName { get; private set; }
        public string lder_lokalafdelingName { get; private set; }
        public string CreatedByYomiName { get; private set; }
        public string MasterContactIdYomiName { get; private set; }
        public string lder_jobcenterafmeldekodeName { get; private set; }
        public string PreferredEquipmentIdName { get; private set; }
        public string MasterContactIdName { get; private set; }
        public string OriginatingLeadIdYomiName { get; private set; }
        public string EntityImage_Timestamp { get; private set; }
        public string ModifiedByName { get; private set; }
        public string lder_sprogName { get; private set; }
        public string lder_stillingskodeName { get; private set; }
        public string lder_under_indmeldelse_i_foreningName { get; private set; }
        public string lder_foreningName { get; private set; }
        public string ModifiedOnBehalfByName { get; private set; }
        public string CreatedOnBehalfByYomiName { get; private set; }
        public string lder_ansaettelsesforholdName { get; private set; }
        public string ModifiedOnBehalfByYomiName { get; private set; }
        public string lder_medlemskategoriName { get; private set; }
        public string PreferredServiceIdName { get; private set; }
        public string DefaultPriceLevelIdName { get; private set; }
        public string lder_moedelokationName { get; private set; }
        public string OriginatingLeadIdName { get; private set; }
        public string CreatedByName { get; private set; }
        public string ModifiedByYomiName { get; private set; }
        public string TransactionCurrencyIdName { get; private set; }
        public string PreferredSystemUserIdName { get; private set; }
        public string PreferredSystemUserIdYomiName { get; private set; }
        public string Address1_AddressTypeCode { get; private set; }
        public string Address1_City { get; private set; }
        public string Address1_Composite { get; private set; }
        public string Address1_Country { get; private set; }
        public string Address1_County { get; private set; }
        public string Address1_AddressId { get; private set; }
        public string Address1_Fax { get; private set; }
        public string Address1_FreightTermsCode { get; private set; }
        public string Address1_Latitude { get; private set; }
        public string Address1_Line1 { get; private set; }
        public string Address1_Line2 { get; private set; }
        public string Address1_Line3 { get; private set; }
        public string Address1_Longitude { get; private set; }
        public string Address1_Name { get; private set; }
        public string Address1_PostalCode { get; private set; }
        public string Address1_PostOfficeBox { get; private set; }
        public string Address1_PrimaryContactName { get; private set; }
        public string Address1_ShippingMethodCode { get; private set; }
        public string Address1_StateOrProvince { get; private set; }
        public string Address1_Telephone1 { get; private set; }
        public string Address1_Telephone2 { get; private set; }
        public string Address1_Telephone3 { get; private set; }
        public string Address1_UPSZone { get; private set; }
        public string Address1_UTCOffset { get; private set; }
        public string Address2_AddressTypeCode { get; private set; }
        public string Address2_City { get; private set; }
        public string Address2_Composite { get; private set; }
        public string Address2_Country { get; private set; }
        public string Address2_County { get; private set; }
        public string Address2_AddressId { get; private set; }
        public string Address2_Fax { get; private set; }
        public string Address2_FreightTermsCode { get; private set; }
        public string Address2_Latitude { get; private set; }
        public string Address2_Line1 { get; private set; }
        public string Address2_Line2 { get; private set; }
        public string Address2_Line3 { get; private set; }
        public string Address2_Longitude { get; private set; }
        public string Address2_Name { get; private set; }
        public string Address2_PostalCode { get; private set; }
        public string Address2_PostOfficeBox { get; private set; }
        public string Address2_PrimaryContactName { get; private set; }
        public string Address2_ShippingMethodCode { get; private set; }
        public string Address2_StateOrProvince { get; private set; }
        public string Address2_Telephone1 { get; private set; }
        public string Address2_Telephone2 { get; private set; }
        public string Address2_Telephone3 { get; private set; }
        public string Address2_UPSZone { get; private set; }
        public string Address2_UTCOffset { get; private set; }
        public string Address3_AddressTypeCode { get; private set; }
        public string Address3_City { get; private set; }
        public string Address3_Composite { get; private set; }
        public string Address3_Country { get; private set; }
        public string Address3_County { get; private set; }
        public string Address3_AddressId { get; private set; }
        public string Address3_Fax { get; private set; }
        public string Address3_FreightTermsCode { get; private set; }
        public string Address3_Latitude { get; private set; }
        public string Address3_Line1 { get; private set; }
        public string Address3_Line2 { get; private set; }
        public string Address3_Line3 { get; private set; }
        public string Address3_Longitude { get; private set; }
        public string Address3_Name { get; private set; }
        public string Address3_PostalCode { get; private set; }
        public string Address3_PostOfficeBox { get; private set; }
        public string Address3_PrimaryContactName { get; private set; }
        public string Address3_ShippingMethodCode { get; private set; }
        public string Address3_StateOrProvince { get; private set; }
        public string Address3_Telephone1 { get; private set; }
        public string Address3_Telephone2 { get; private set; }
        public string Address3_Telephone3 { get; private set; }
        public string Address3_UPSZone { get; private set; }
        public string Address3_UTCOffset { get; private set; }
        public string OwnerId { get; private set; }
        public string OwnerIdName { get; private set; }
        public string OwnerIdYomiName { get; private set; }
        public string OwnerIdDsc { get; private set; }
        public string OwnerIdType { get; private set; }
        public string OwningUser { get; private set; }
        public string OwningTeam { get; private set; }
        public string AccountId { get; private set; }
        public string AccountIdName { get; private set; }
        public string AccountIdYomiName { get; private set; }
        public string ParentContactId { get; private set; }
        public string ParentContactIdName { get; private set; }
        public string ParentContactIdYomiName { get; private set; }
        public string ContactId { get; private set; }
        public string DefaultPriceLevelId { get; private set; }
        public string CustomerSizeCode { get; private set; }
        public string CustomerTypeCode { get; private set; }
        public string PreferredContactMethodCode { get; private set; }
        public string LeadSourceCode { get; private set; }
        public string OriginatingLeadId { get; private set; }
        public string OwningBusinessUnit { get; private set; }
        public string PaymentTermsCode { get; private set; }
        public string ShippingMethodCode { get; private set; }
        public string ParticipatesInWorkflow { get; private set; }
        public string IsBackofficeCustomer { get; private set; }
        public string Salutation { get; private set; }
        public string JobTitle { get; private set; }
        public string FirstName { get; private set; }
        public string Department { get; private set; }
        public string NickName { get; private set; }
        public string MiddleName { get; private set; }
        public string LastName { get; private set; }
        public string Suffix { get; private set; }
        public string YomiFirstName { get; private set; }
        public string FullName { get; private set; }
        public string YomiMiddleName { get; private set; }
        public string YomiLastName { get; private set; }
        public string Anniversary { get; private set; }
        public string BirthDate { get; private set; }
        public string GovernmentId { get; private set; }
        public string YomiFullName { get; private set; }
        public string Description { get; private set; }
        public string EmployeeId { get; private set; }
        public string GenderCode { get; private set; }
        public string AnnualIncome { get; private set; }
        public string HasChildrenCode { get; private set; }
        public string EducationCode { get; private set; }
        public string WebSiteUrl { get; private set; }
        public string FamilyStatusCode { get; private set; }
        public string FtpSiteUrl { get; private set; }
        public string EMailAddress1 { get; private set; }
        public string SpousesName { get; private set; }
        public string AssistantName { get; private set; }
        public string EMailAddress2 { get; private set; }
        public string AssistantPhone { get; private set; }
        public string EMailAddress3 { get; private set; }
        public string DoNotPhone { get; private set; }
        public string ManagerName { get; private set; }
        public string ManagerPhone { get; private set; }
        public string DoNotFax { get; private set; }
        public string DoNotEMail { get; private set; }
        public string DoNotPostalMail { get; private set; }
        public string DoNotBulkEMail { get; private set; }
        public string DoNotBulkPostalMail { get; private set; }
        public string AccountRoleCode { get; private set; }
        public string TerritoryCode { get; private set; }
        public string IsPrivate { get; private set; }
        public string CreditLimit { get; private set; }
        public string CreatedOn { get; private set; }
        public string CreditOnHold { get; private set; }
        public string CreatedBy { get; private set; }
        public string ModifiedOn { get; private set; }
        public string ModifiedBy { get; private set; }
        public string NumberOfChildren { get; private set; }
        public string ChildrensNames { get; private set; }
        public string VersionNumber { get; private set; }
        public string MobilePhone { get; private set; }
        public string Pager { get; private set; }
        public string Telephone1 { get; private set; }
        public string Telephone2 { get; private set; }
        public string Telephone3 { get; private set; }
        public string Fax { get; private set; }
        public string Aging30 { get; private set; }
        public string StateCode { get; private set; }
        public string Aging60 { get; private set; }
        public string StatusCode { get; private set; }
        public string Aging90 { get; private set; }
        public string PreferredSystemUserId { get; private set; }
        public string PreferredServiceId { get; private set; }
        public string MasterId { get; private set; }
        public string PreferredAppointmentDayCode { get; private set; }
        public string PreferredAppointmentTimeCode { get; private set; }
        public string DoNotSendMM { get; private set; }
        public string ParentCustomerId { get; private set; }
        public string Merged { get; private set; }
        public string ExternalUserIdentifier { get; private set; }
        public string SubscriptionId { get; private set; }
        public string PreferredEquipmentId { get; private set; }
        public string LastUsedInCampaign { get; private set; }
        public string ParentCustomerIdName { get; private set; }
        public string ParentCustomerIdType { get; private set; }
        public string TransactionCurrencyId { get; private set; }
        public string OverriddenCreatedOn { get; private set; }
        public string ExchangeRate { get; private set; }
        public string ImportSequenceNumber { get; private set; }
        public string TimeZoneRuleVersionNumber { get; private set; }
        public string UTCConversionTimeZoneCode { get; private set; }
        public string AnnualIncome_Base { get; private set; }
        public string CreditLimit_Base { get; private set; }
        public string Aging60_Base { get; private set; }
        public string Aging90_Base { get; private set; }
        public string Aging30_Base { get; private set; }
        public string ParentCustomerIdYomiName { get; private set; }
        public string CreatedOnBehalfBy { get; private set; }
        public string ModifiedOnBehalfBy { get; private set; }
        public string IsAutoCreate { get; private set; }
        public string StageId { get; private set; }
        public string ProcessId { get; private set; }
        public string EntityImageId { get; private set; }
        public string TraversedPath { get; private set; }
        public string Business2 { get; private set; }
        public string Callback { get; private set; }
        public string Company { get; private set; }
        public string Home2 { get; private set; }
        public string Ap_webbrugernavn { get; private set; }
        public string Ap_Medlemstype { get; private set; }
        public string Ap_emailvask { get; private set; }
        public string Ap_Emailugyldig { get; private set; }
        public string Ap_Emailvasketprdato { get; private set; }
        public string Ap_Senestedatoforweblogin { get; private set; }
        public string Ap_senestelogintype { get; private set; }
        public string Ap_WebUserID { get; private set; }
        public string nn_nndecisionmakerid { get; private set; }
        public string nn_updateprotected { get; private set; }
        public string Ap_Restance { get; private set; }
        public string Ap_Address2MunicipalityCode { get; private set; }
        public string AP_Branchenummer { get; private set; }
        public string Ap_Servicenyhedsbrev { get; private set; }
        public string Ap_testcontact { get; private set; }
        public string AP_Uddannelsesbaggrund { get; private set; }
        public string AP_Newsletteremail { get; private set; }
        public string Ap_Efterloendato { get; private set; }
        public string Ap_Efterloen { get; private set; }
        public string AP_Member { get; private set; }
        public string Ap_Tilbudtildig { get; private set; }
        public string Ap_Tidligereakasse { get; private set; }
        public string Ap_Address2CountyCode { get; private set; }
        public string Ap_Pensionistdato { get; private set; }
        public string Ap_Ledigdato { get; private set; }
        public string Ap_Medlemsdatasenestopdateret { get; private set; }
        public string AP_Newsletter { get; private set; }
        public string Lh_Tillgsforsikring { get; private set; }
        public string Ap_Uddannelse { get; private set; }
        public string Ap_Paneler { get; private set; }
        public string AP_Ledig { get; private set; }
        public string AP_Pensionist { get; private set; }
        public string Ap_Udmeldafnuvaerendeorganisation { get; private set; }
        public string AP_LeadID { get; private set; }
        public string AP_Ansaettelsessted { get; private set; }
        public string AP_Indmeldtiakasse { get; private set; }
        public string AP_Branchenavn { get; private set; }
        public string AP_NyStilling { get; private set; }
        public string Ap_Kontonummer { get; private set; }
        public string Ap_birthdate { get; private set; }
        public string AP_Efterlonsbidrag { get; private set; }
        public string Ap_SMS { get; private set; }
        public string Ap_Kurserogkonferencer { get; private set; }
        public string Ap_Regnr { get; private set; }
        public string AP_Tillidserhverv { get; private set; }
        public string AP_MemberNumber { get; private set; }
        public string AP_Kursist { get; private set; }
        public string AP_Akasse { get; private set; }
        public string AP_Indmeldtiorganisation { get; private set; }
        public string Ap_Medlemunderoptagelse { get; private set; }
        public string Ap_Momsregistreretvedoptagelse { get; private set; }
        public string Ap_Nyhedsbrevsabonnent { get; private set; }
        public string AP_Organisation { get; private set; }
        public string AP_County { get; private set; }
        public string Ap_Fraflyttetakasse { get; private set; }
        public string Ap_Address2Municipality { get; private set; }
        public string AP_Sprogkundskaber { get; private set; }
        public string AP_Alder { get; private set; }
        public string Ap_Udmeldt { get; private set; }
        public string AP_Tillidsposter { get; private set; }
        public string Lh_NavisionID { get; private set; }
        public string ap_Doed { get; private set; }
        public string ap_LTDaekning { get; private set; }
        public string ap_LTKarens { get; private set; }
        public string ap_LTPeriode { get; private set; }
        public string ap_Ulykkesforsikring { get; private set; }
        public string ap_LTIkraftdato { get; private set; }
        public string ap_managementlevel { get; private set; }
        public string ap_opdateretfraweb { get; private set; }
        public string ap_Privatforsikringer { get; private set; }
        public string ap_Sundhedsforsikring { get; private set; }
        public string ap_Forening { get; private set; }
        public string ap_KCContactGUID { get; private set; }
        public string ap_Mobilnummerlandekode { get; private set; }
        public string ap_SMSgatewayadresse { get; private set; }
        public string lder_stillingskode { get; private set; }
        public string lder_forbundsenhed { get; private set; }
        public string lder_lokalafdeling { get; private set; }
        public string lder_forening { get; private set; }
        public string lder_address2_kommune { get; private set; }
        public string lder_address2_landekode_og_land { get; private set; }
        public string lder_address2_postnummer_og_by { get; private set; }
        public string lder_address2region { get; private set; }
        public string lder_afmeldt_jobcenter { get; private set; }
        public string lder_akasse_framelding { get; private set; }
        public string lder_akasse_indmelding { get; private set; }
        public string lder_dagpengeretsdato { get; private set; }
        public string lder_digital_kommunikation_fravalgt { get; private set; }
        public string lder_dimittenddato { get; private set; }
        public string lder_efterloensbevis_pr_dato { get; private set; }
        public string lder_efterloensordning_pr { get; private set; }
        public string lder_efterloesnbidrag { get; private set; }
        public string lder_ej_ret_til_juridisk_hjaelp { get; private set; }
        public string lder_foerstkommende_moededato_i_akassen { get; private set; }
        public string lder_forsikringsform { get; private set; }
        public string lder_hemmelig_adresse { get; private set; }
        public string lder_knap_data { get; private set; }
        public string lder_landekode { get; private set; }
        public string lder_landekode_alternativnummer { get; private set; }
        public string lder_landekode_mobilnummer { get; private set; }
        public string lder_maa_tilbydes_a_kasse { get; private set; }
        public string lder_maa_tilbydes_coaching { get; private set; }
        public string lder_maa_tilbydes_kurser { get; private set; }
        public string lder_maa_tilbydes_organisation { get; private set; }
        public string lder_maa_tilbydes_outplacement { get; private set; }
        public string lder_maa_tilbydes_pension { get; private set; }
        public string lder_maa_tilbydes_privatforsikring { get; private set; }
        public string lder_maa_tilbydes_sundhedsforsikring { get; private set; }
        public string lder_maa_tilbydes_tillaegsforsikring { get; private set; }
        public string lder_maa_tilbydes_ulykkesforsikring { get; private set; }
        public string lder_medlemstype { get; private set; }
        public string lder_modulusid { get; private set; }
        public string lder_senest_tilbudt_coaching { get; private set; }
        public string lder_senest_tilbudt_kurser { get; private set; }
        public string lder_senest_tilbudt_outplacement { get; private set; }
        public string lder_senest_tilbudt_pension { get; private set; }
        public string lder_senest_tilbudt_privatforsikring { get; private set; }
        public string lder_tillidshverv { get; private set; }
        public string lder_tilmeldt_jobcenter { get; private set; }
        public string lder_tilmeldt_jobcenter_ja_nej { get; private set; }
        public string lder_vaesentlige_bemaerkninger { get; private set; }
        public string lder_ansaettelsesforhold { get; private set; }
        public string lder_under_indmeldelse_i_forening { get; private set; }
        public string lder_jobcenterafmeldekode { get; private set; }
        public string lder_medlemskategori { get; private set; }
        public string lder_fremtidig_forening { get; private set; }
        public string lder_ej_tilfredshedsmling { get; private set; }
        public string lder_moedelokation { get; private set; }
        public string lder_sprog { get; private set; }
        public string lder_dato_for_seneste_afholdte_cv_samtale { get; private set; }
        public string lder_klipforbrug { get; private set; }     
    }
}
