using System;

namespace CluedIn.Crawling.Dynamics365.Core.Models
{
    public class EntityDefinition
    {
        public int ActivityTypeMask { get; set; }
        public bool AutoRouteToOwnerQueue { get; set; }
        public bool CanTriggerWorkflow { get; set; }
        public bool EntityHelpUrlEnabled { get; set; }
        public string EntityHelpUrl { get; set; }
        public bool IsDocumentManagementEnabled { get; set; }
        public bool IsOneNoteIntegrationEnabled { get; set; }
        public bool IsInteractionCentricEnabled { get; set; }
        public bool IsKnowledgeManagementEnabled { get; set; }
        public bool IsSLAEnabled { get; set; }
        public bool IsBPFEntity { get; set; }
        public bool IsDocumentRecommendationsEnabled { get; set; }
        public bool IsMSTeamsIntegrationEnabled { get; set; }
        public object SettingOf { get; set; }
        public string DataProviderId { get; set; }
        public string DataSourceId { get; set; }
        public bool AutoCreateAccessTeams { get; set; }
        public bool IsActivity { get; set; }
        public bool IsActivityParty { get; set; }
        public bool IsAvailableOffline { get; set; }
        public bool IsChildEntity { get; set; }
        public bool IsAIRUpdated { get; set; }
        public object IconLargeName { get; set; }
        public string IconMediumName { get; set; }
        public string IconSmallName { get; set; }
        public string IconVectorName { get; set; }
        public bool IsCustomEntity { get; set; }
        public bool IsBusinessProcessEnabled { get; set; }
        public bool SyncToExternalSearchIndex { get; set; }
        public bool IsOptimisticConcurrencyEnabled { get; set; }
        public bool ChangeTrackingEnabled { get; set; }
        public bool IsImportable { get; set; }
        public bool IsIntersect { get; set; }
        public bool IsManaged { get; set; }
        public bool IsEnabledForCharts { get; set; }
        public bool IsEnabledForTrace { get; set; }
        public bool IsValidForAdvancedFind { get; set; }
        public int DaysSinceRecordLastModified { get; set; }
        public string MobileOfflineFilters { get; set; }
        public bool IsReadingPaneEnabled { get; set; }
        public bool IsQuickCreateEnabled { get; set; }
        public string LogicalName { get; set; }
        public int ObjectTypeCode { get; set; }
        public string OwnershipType { get; set; }
        public string PrimaryNameAttribute { get; set; }
        public string PrimaryImageAttribute { get; set; }
        public string PrimaryIdAttribute { get; set; }
        public string RecurrenceBaseEntityLogicalName { get; set; }
        public string ReportViewName { get; set; }
        public string SchemaName { get; set; }
        public string IntroducedVersion { get; set; }
        public bool IsStateModelAware { get; set; }
        public bool EnforceStateTransitions { get; set; }
        public string ExternalName { get; set; }
        public string EntityColor { get; set; }
        public string LogicalCollectionName { get; set; }
        public string ExternalCollectionName { get; set; }
        public string CollectionSchemaName { get; set; }
        public string EntitySetName { get; set; }
        public bool IsEnabledForExternalChannels { get; set; }
        public bool IsPrivate { get; set; }
        public bool UsesBusinessDataLabelTable { get; set; }
        public bool IsLogicalEntity { get; set; }
        public bool HasNotes { get; set; }
        public bool HasActivities { get; set; }
        public bool HasFeedback { get; set; }
        public bool IsSolutionAware { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime ModifiedOn { get; set; }
        public string MetadataId { get; set; }
        public object HasChanged { get; set; }
        public Description Description { get; set; }
        public Displaycollectionname DisplayCollectionName { get; set; }
        public Displayname DisplayName { get; set; }
        public Isconnectionsenabled IsAuditEnabled { get; set; }
        public Isvalidforqueue IsValidForQueue { get; set; }
        public Isconnectionsenabled IsConnectionsEnabled { get; set; }
        public Iscustomizable IsCustomizable { get; set; }
        public Ismappable IsRenameable { get; set; }
        public Ismappable IsMappable { get; set; }
        public Ismappable IsDuplicateDetectionEnabled { get; set; }
        public Ismappable CanCreateAttributes { get; set; }
        public Ismappable CanCreateForms { get; set; }
        public Ismappable CanCreateViews { get; set; }
        public Ismappable CanCreateCharts { get; set; }
        public Ismappable CanBeRelatedEntityInRelationship { get; set; }
        public Ismappable CanBePrimaryEntityInRelationship { get; set; }
        public Ismappable CanBeInManyToMany { get; set; }
        public Ismappable CanBeInCustomEntityAssociation { get; set; }
        public Ismappable CanEnableSyncToExternalSearchIndex { get; set; }
        public Ismappable CanModifyAdditionalSettings { get; set; }
        public Ismappable CanChangeHierarchicalRelationship { get; set; }
        public Ismappable CanChangeTrackingBeEnabled { get; set; }
        public Ismappable IsMailMergeEnabled { get; set; }
        public Ismappable IsVisibleInMobile { get; set; }
        public Ismappable IsVisibleInMobileClient { get; set; }
        public Ismappable IsReadOnlyInMobileClient { get; set; }
        public Ismappable IsOfflineInMobileClient { get; set; }
        public Privilege[] Privileges { get; set; }
        public object[] Settings { get; set; }
        public Attribute[] Attributes { get; set; }
    }

}
